name: PDX Quantum Computing Reading Group
markdown: kramdown

collections:
    bibentries:
        output: true
        permalink: /:collection/:name
        values:
            layout: bibentry
    topics:
        output: true
        permalink: /:name
        values:
            layout: topic

theme: jekyll-theme-minimal
