name: PDX Quantum Computing Reading Group
markdown: kramdown

collections:
  bibentries:
    output: true
    permalink: /:collection/:name
  topics:
    output: true
    permalink: /:name
defaults:
  - scope:
      path: ""
      type: bibentries
    values:
      layout: bibentry
  - scope:
      path: ""
      type: topics
    values:
      layout: topic
