name: PDX Quantum Computing Reading Group
markdown: kramdown

collections:
    bibentries:
        output: true
        permalink: /:collection/:name
        defaults:
            values:
                layout: bibentry
    topics:
        output: true
        permalink: /:name
        defaults:
            values:
                layout: topic

theme: jekyll-theme-minimal
